// This is an example of a folder based connection module.
// Prismas interface is generated by prisma, so is here simply imported
// and exported as the modules interface.

const { prisma } = require('./../../../database/generated/prisma-client');

module.exports = {
  name: 'prisma',
  interface: prisma
};